// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPortForward(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddPortForward'](arg1, arg2, arg3, arg4);
}

export function ChangeDir(arg1, arg2) {
  return window['go']['main']['App']['ChangeDir'](arg1, arg2);
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function CopyFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['CopyFile'](arg1, arg2, arg3);
}

export function CurrentTokenOwner(arg1) {
  return window['go']['main']['App']['CurrentTokenOwner'](arg1);
}

export function DeleteBuild(arg1) {
  return window['go']['main']['App']['DeleteBuild'](arg1);
}

export function DeleteImplantProfile(arg1) {
  return window['go']['main']['App']['DeleteImplantProfile'](arg1);
}

export function DeleteLoot(arg1) {
  return window['go']['main']['App']['DeleteLoot'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function DownloadFile(arg1, arg2) {
  return window['go']['main']['App']['DownloadFile'](arg1, arg2);
}

export function DownloadFileTo(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadFileTo'](arg1, arg2, arg3);
}

export function DownloadLoot(arg1) {
  return window['go']['main']['App']['DownloadLoot'](arg1);
}

export function ExecuteAssembly(arg1, arg2) {
  return window['go']['main']['App']['ExecuteAssembly'](arg1, arg2);
}

export function ExecuteBeaconCommand(arg1, arg2) {
  return window['go']['main']['App']['ExecuteBeaconCommand'](arg1, arg2);
}

export function ExecuteBeaconCommandAsync(arg1, arg2) {
  return window['go']['main']['App']['ExecuteBeaconCommandAsync'](arg1, arg2);
}

export function ExecuteCommand(arg1, arg2) {
  return window['go']['main']['App']['ExecuteCommand'](arg1, arg2);
}

export function GenerateImplant(arg1) {
  return window['go']['main']['App']['GenerateImplant'](arg1);
}

export function GetBeaconTaskResult(arg1) {
  return window['go']['main']['App']['GetBeaconTaskResult'](arg1);
}

export function GetBeaconTasks(arg1) {
  return window['go']['main']['App']['GetBeaconTasks'](arg1);
}

export function GetBuildHistory() {
  return window['go']['main']['App']['GetBuildHistory']();
}

export function GetEnvVars(arg1) {
  return window['go']['main']['App']['GetEnvVars'](arg1);
}

export function GetLoot() {
  return window['go']['main']['App']['GetLoot']();
}

export function GetNetstat(arg1) {
  return window['go']['main']['App']['GetNetstat'](arg1);
}

export function GetPrivs(arg1) {
  return window['go']['main']['App']['GetPrivs'](arg1);
}

export function GetProcessList(arg1) {
  return window['go']['main']['App']['GetProcessList'](arg1);
}

export function GetSystem(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetSystem'](arg1, arg2, arg3);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function Ifconfig(arg1) {
  return window['go']['main']['App']['Ifconfig'](arg1);
}

export function ImpersonateUser(arg1, arg2) {
  return window['go']['main']['App']['ImpersonateUser'](arg1, arg2);
}

export function KillBeacon(arg1) {
  return window['go']['main']['App']['KillBeacon'](arg1);
}

export function KillJob(arg1) {
  return window['go']['main']['App']['KillJob'](arg1);
}

export function KillRemoteProcess(arg1, arg2) {
  return window['go']['main']['App']['KillRemoteProcess'](arg1, arg2);
}

export function KillSession(arg1) {
  return window['go']['main']['App']['KillSession'](arg1);
}

export function ListBeacons() {
  return window['go']['main']['App']['ListBeacons']();
}

export function ListC2Profiles() {
  return window['go']['main']['App']['ListC2Profiles']();
}

export function ListFiles(arg1, arg2) {
  return window['go']['main']['App']['ListFiles'](arg1, arg2);
}

export function ListImplantProfiles() {
  return window['go']['main']['App']['ListImplantProfiles']();
}

export function ListJobs() {
  return window['go']['main']['App']['ListJobs']();
}

export function ListOperators() {
  return window['go']['main']['App']['ListOperators']();
}

export function ListPivots(arg1) {
  return window['go']['main']['App']['ListPivots'](arg1);
}

export function ListPortForwards(arg1) {
  return window['go']['main']['App']['ListPortForwards'](arg1);
}

export function ListServices(arg1) {
  return window['go']['main']['App']['ListServices'](arg1);
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function ListenerC2Options() {
  return window['go']['main']['App']['ListenerC2Options']();
}

export function LootFile(arg1, arg2) {
  return window['go']['main']['App']['LootFile'](arg1, arg2);
}

export function MakeDirectory(arg1, arg2) {
  return window['go']['main']['App']['MakeDirectory'](arg1, arg2);
}

export function MakeToken(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['MakeToken'](arg1, arg2, arg3, arg4);
}

export function MoveFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['MoveFile'](arg1, arg2, arg3);
}

export function PickConfigFile() {
  return window['go']['main']['App']['PickConfigFile']();
}

export function PrintWorkingDir(arg1) {
  return window['go']['main']['App']['PrintWorkingDir'](arg1);
}

export function ProcessDump(arg1, arg2) {
  return window['go']['main']['App']['ProcessDump'](arg1, arg2);
}

export function ReadRemoteFile(arg1, arg2) {
  return window['go']['main']['App']['ReadRemoteFile'](arg1, arg2);
}

export function RegistryCreateKey(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RegistryCreateKey'](arg1, arg2, arg3, arg4);
}

export function RegistryDeleteKey(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RegistryDeleteKey'](arg1, arg2, arg3, arg4);
}

export function RegistryListSubKeys(arg1, arg2, arg3) {
  return window['go']['main']['App']['RegistryListSubKeys'](arg1, arg2, arg3);
}

export function RegistryListValues(arg1, arg2, arg3) {
  return window['go']['main']['App']['RegistryListValues'](arg1, arg2, arg3);
}

export function RegistryReadValue(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RegistryReadValue'](arg1, arg2, arg3, arg4);
}

export function RegistryWriteValue(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['RegistryWriteValue'](arg1, arg2, arg3, arg4, arg5);
}

export function RemoveFile(arg1, arg2) {
  return window['go']['main']['App']['RemoveFile'](arg1, arg2);
}

export function RemovePortForward(arg1, arg2) {
  return window['go']['main']['App']['RemovePortForward'](arg1, arg2);
}

export function RemoveService(arg1, arg2, arg3) {
  return window['go']['main']['App']['RemoveService'](arg1, arg2, arg3);
}

export function RenameSession(arg1, arg2) {
  return window['go']['main']['App']['RenameSession'](arg1, arg2);
}

export function RevToSelf(arg1) {
  return window['go']['main']['App']['RevToSelf'](arg1);
}

export function RunExecute(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunExecute'](arg1, arg2, arg3);
}

export function SaveImplantProfile(arg1) {
  return window['go']['main']['App']['SaveImplantProfile'](arg1);
}

export function SetEnvVar(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetEnvVar'](arg1, arg2, arg3);
}

export function Sideload(arg1, arg2, arg3) {
  return window['go']['main']['App']['Sideload'](arg1, arg2, arg3);
}

export function SocksProxyStatus(arg1) {
  return window['go']['main']['App']['SocksProxyStatus'](arg1);
}

export function StartDNSListener(arg1) {
  return window['go']['main']['App']['StartDNSListener'](arg1);
}

export function StartHTTPListener(arg1) {
  return window['go']['main']['App']['StartHTTPListener'](arg1);
}

export function StartMTLSListener(arg1) {
  return window['go']['main']['App']['StartMTLSListener'](arg1);
}

export function StartPivotListener(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartPivotListener'](arg1, arg2, arg3);
}

export function StartService(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartService'](arg1, arg2, arg3, arg4);
}

export function StartSocksProxy(arg1, arg2) {
  return window['go']['main']['App']['StartSocksProxy'](arg1, arg2);
}

export function StartWGListener(arg1) {
  return window['go']['main']['App']['StartWGListener'](arg1);
}

export function StopPivotListener(arg1, arg2) {
  return window['go']['main']['App']['StopPivotListener'](arg1, arg2);
}

export function StopService(arg1, arg2, arg3) {
  return window['go']['main']['App']['StopService'](arg1, arg2, arg3);
}

export function StopSocksProxy(arg1) {
  return window['go']['main']['App']['StopSocksProxy'](arg1);
}

export function TakeScreenshot(arg1) {
  return window['go']['main']['App']['TakeScreenshot'](arg1);
}

export function UnsetEnvVar(arg1, arg2) {
  return window['go']['main']['App']['UnsetEnvVar'](arg1, arg2);
}

export function UploadFile(arg1, arg2) {
  return window['go']['main']['App']['UploadFile'](arg1, arg2);
}

export function UploadFileFrom(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadFileFrom'](arg1, arg2, arg3);
}
