// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddPortForward(arg1:string,arg2:number,arg3:string,arg4:number):Promise<void>;

export function ChangeDir(arg1:string,arg2:string):Promise<string>;

export function Connect(arg1:string):Promise<main.ConnectResult>;

export function CopyFile(arg1:string,arg2:string,arg3:string):Promise<number>;

export function CurrentTokenOwner(arg1:string):Promise<string>;

export function DeleteBuild(arg1:string):Promise<void>;

export function DeleteImplantProfile(arg1:string):Promise<void>;

export function DeleteLoot(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function DownloadFile(arg1:string,arg2:string):Promise<main.TransferResult>;

export function DownloadFileTo(arg1:string,arg2:string,arg3:string):Promise<main.TransferResult>;

export function DownloadLoot(arg1:string):Promise<main.TransferResult>;

export function ExecuteAssembly(arg1:string,arg2:string):Promise<main.AssemblyResult>;

export function ExecuteBeaconCommand(arg1:string,arg2:string):Promise<main.BeaconTaskResult>;

export function ExecuteBeaconCommandAsync(arg1:string,arg2:string):Promise<main.BeaconTaskResult>;

export function ExecuteCommand(arg1:string,arg2:string):Promise<main.ExecResult>;

export function GenerateImplant(arg1:main.GenerateRequest):Promise<main.GenerateResult>;

export function GetBeaconTaskResult(arg1:string):Promise<main.BeaconTaskView>;

export function GetBeaconTasks(arg1:string):Promise<Array<main.BeaconTaskView>>;

export function GetBuildHistory():Promise<Array<main.BuildView>>;

export function GetEnvVars(arg1:string):Promise<Array<main.EnvVar>>;

export function GetLoot():Promise<Array<main.LootView>>;

export function GetNetstat(arg1:string):Promise<Array<main.NetstatEntry>>;

export function GetPrivs(arg1:string):Promise<main.PrivsResult>;

export function GetProcessList(arg1:string):Promise<Array<main.ProcessView>>;

export function GetSystem(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetVersion():Promise<main.VersionInfo>;

export function Ifconfig(arg1:string):Promise<Array<main.NetInterfaceView>>;

export function ImpersonateUser(arg1:string,arg2:string):Promise<void>;

export function KillBeacon(arg1:string):Promise<void>;

export function KillJob(arg1:number):Promise<void>;

export function KillRemoteProcess(arg1:string,arg2:number):Promise<void>;

export function KillSession(arg1:string):Promise<void>;

export function ListBeacons():Promise<Array<main.BeaconView>>;

export function ListC2Profiles():Promise<Array<main.C2ProfileView>>;

export function ListFiles(arg1:string,arg2:string):Promise<main.LsResult>;

export function ListImplantProfiles():Promise<Array<main.ProfileView>>;

export function ListJobs():Promise<Array<main.JobView>>;

export function ListOperators():Promise<Array<main.OperatorView>>;

export function ListPivots(arg1:string):Promise<Array<main.PivotView>>;

export function ListPortForwards(arg1:string):Promise<Array<main.PortForwardView>>;

export function ListServices(arg1:string):Promise<Array<main.ServiceView>>;

export function ListSessions():Promise<Array<main.SessionView>>;

export function ListenerC2Options():Promise<Array<string>>;

export function LootFile(arg1:string,arg2:string):Promise<void>;

export function MakeDirectory(arg1:string,arg2:string):Promise<void>;

export function MakeToken(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function MoveFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function PickConfigFile():Promise<string>;

export function PrintWorkingDir(arg1:string):Promise<string>;

export function ProcessDump(arg1:string,arg2:number):Promise<main.TransferResult>;

export function ReadRemoteFile(arg1:string,arg2:string):Promise<string>;

export function RegistryCreateKey(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function RegistryDeleteKey(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function RegistryListSubKeys(arg1:string,arg2:string,arg3:string):Promise<Array<string>>;

export function RegistryListValues(arg1:string,arg2:string,arg3:string):Promise<Array<main.RegistryValue>>;

export function RegistryReadValue(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function RegistryWriteValue(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function RemoveFile(arg1:string,arg2:string):Promise<void>;

export function RemovePortForward(arg1:string,arg2:number):Promise<void>;

export function RemoveService(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RenameSession(arg1:string,arg2:string):Promise<void>;

export function RevToSelf(arg1:string):Promise<void>;

export function RunExecute(arg1:string,arg2:string,arg3:Array<string>):Promise<main.ExecResult>;

export function SaveImplantProfile(arg1:main.GenerateRequest):Promise<void>;

export function SetEnvVar(arg1:string,arg2:string,arg3:string):Promise<void>;

export function Sideload(arg1:string,arg2:string,arg3:string):Promise<main.AssemblyResult>;

export function SocksProxyStatus(arg1:string):Promise<number>;

export function StartDNSListener(arg1:main.StartDNSReq):Promise<void>;

export function StartHTTPListener(arg1:main.StartHTTPReq):Promise<void>;

export function StartMTLSListener(arg1:main.StartMTLSReq):Promise<void>;

export function StartPivotListener(arg1:string,arg2:string,arg3:string):Promise<void>;

export function StartService(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function StartSocksProxy(arg1:string,arg2:number):Promise<void>;

export function StartWGListener(arg1:main.StartWGReq):Promise<void>;

export function StopPivotListener(arg1:string,arg2:number):Promise<void>;

export function StopService(arg1:string,arg2:string,arg3:string):Promise<void>;

export function StopSocksProxy(arg1:string):Promise<void>;

export function TakeScreenshot(arg1:string):Promise<string>;

export function UnsetEnvVar(arg1:string,arg2:string):Promise<void>;

export function UploadFile(arg1:string,arg2:string):Promise<main.TransferResult>;

export function UploadFileFrom(arg1:string,arg2:string,arg3:string):Promise<main.TransferResult>;
